"""phase3

Revision ID: 10ac1eff40b7
Revises: 51d88fef4555
Create Date: 2026-05-18 20:53:09.660137

"""
from alembic import op
import sqlalchemy as sa


revision = '10ac1eff40b7'
down_revision = '51d88fef4555'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('page_id', 'language')
    )
    op.add_column('pages', sa.Column('language', sa.String(length=10), nullable=True))
    op.add_column('systems', sa.Column('translatable', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('systems', 'translatable')
    op.drop_column('pages', 'language')
    op.drop_table('page_translations')
    # ### end Alembic commands ###
